// Type-only re-exports from the built wasm-bindgen artifact. Pulls
// from dist/node/ because tsify-next emits identical TS types for both
// targets — the runtime modules differ (init signature, fetch shape)
// but the TS API surface is the same. This avoids consumers having to
// know about target-specific paths to get types.
//
// `dist/node/elevator_wasm.d.ts` is generated by `npm run build`.
// Type-only imports never trigger the runtime module load, so this
// file is safe to compile against on either target.

export type {
	WasmBytesResult,
	WasmSim,
	WasmU32Result,
	WasmU64Result,
	WasmVoidResult,
} from "../dist/node/elevator_wasm";
